
import os
import numpy as np
import matplotlib.pyplot as plt
import netCDF4 as nc4
from matplotlib.gridspec import GridSpec

def retrieve_3D_field_slice(folder, subset, year, month, var_name, depth, iceplume = False):

    year_month = str(year)+'{:02d}'.format(month)
    if iceplume:
        results_dir = 'results_iceplume'
    else:
        results_dir = 'results'

    read_file = ''
    for file_name in os.listdir(os.path.join(folder,results_dir,subset)):
        if file_name.split('.')[1] == year_month:
            read_file = file_name

    if read_file == '':
        raise ValueError(' No file found in '+year_month+' for '+subset)
    else:
        print('Reading from '+read_file)
        ds = nc4.Dataset(os.path.join(folder,results_dir,subset,read_file))
        var_grid = ds.variables[var_name][:, :, :, :]
        depths = ds.variables['depths'][:]
        iterations = ds.variables['iterations'][:]
        ds.close()
        depth_index = np.argmin(np.abs(depths-depth))
        var_grid = var_grid[0, depth_index, :, :]
        depth = depths[depth_index]
        iteration = iterations[0]

    return(depth, iteration, var_grid)

def plot_panels(output_folder,months,grids):

    fig = plt.figure(figsize=(15,7))
    plt.style.use('dark_background')

    vmin = 5
    vmax = 15
    cmap='turbo'

    gs1 = GridSpec(2, 18, left=0.05, right=0.95, top=0.9, bottom=0.05)

    for i in range(len(months)):
        month = months[i]
        if i<4:
            ax = fig.add_subplot(gs1[0,i*4:((i+1)*4)])
        else:
            j=i-3
            ax = fig.add_subplot(gs1[1, j*4:((j+1)*4)])
        grid = grids[i]
        ax.pcolormesh(grid,vmin=vmin,vmax=vmax,cmap=cmap)
        ax.text(520, 15, 'Max:'+"{:.2E}".format(np.max(grid)), color='black', ha='right', va='bottom',
                bbox=dict(facecolor='white', edgecolor='black', boxstyle='round,pad=0.2'))
        ax.set_title('1993/'+str(month))
        ax.set_xticks([])
        ax.set_yticks([])

    ax = fig.add_subplot(gs1[:, -1])
    x = np.array([0,1])
    y = np.linspace(vmin,vmax,100)
    X, Y = np.meshgrid(x,y)
    ax.pcolormesh(X,Y,Y,vmin=vmin,vmax=vmax,cmap=cmap)
    plt.ylabel('NO$_3$ Concentration ($\mu$M)')
    ax.set_xticks([])

    plt.suptitle('Progression of NO$_3$ Generated by Subglacial Discharge Plumes at 100 m depth')

    plt.savefig(output_folder+'/Disko_Bay_NO3_iceplume.png')
    plt.close(fig)



folder = '/Volumes/jakobshavn/Research/Projects/Ocean_Modeling/Projects/Downscale_Darwin/' \
         'darwin3/configurations/downscale_darwin/L2/L2_Disko_Bay'

output_folder = '/Users/mhwood/Documents/Research/Projects/Disko Bay/Figures/L2'

year = 1993

subset = 'BGC_consts_mon_mean'
var_name = 'NO3'
depth = 100
months = [1,2,3,4,6,7,8]

grids = []
for month in [1,2,3,4,6,7,8]:
    model_depth, iteration, iceplume_grid = \
        retrieve_3D_field_slice(folder, subset, year, month, var_name, depth, iceplume = True)
    grids.append(iceplume_grid)

plot_panels(output_folder,months,grids)

print(model_depth)





